
# Đặc điểm tính cách
personality_traits = {
    'T1': 'Hiền lành', 'T2': 'Bướng bỉnh', 'T3': 'Hòa nhã', 'T4': 'Nóng nảy',
    'T5': 'Rộng lượng', 'T6': 'Tự ti', 'T7': 'Lươn lẹo', 'T8': 'Cẩn trọng',
    'T9': 'Nhút nhát', 'T10': 'Tự tin'
}

# Đặc điểm ngoại hình
physical_traits = {
    'H1': 'Mắt sáng', 'H2': 'Mắt to tròn', 'H3': 'Mắt híp', 'H4': 'Sống mũi cao',
    'H5': 'Sống mũi thấp', 'H6': 'Mũi to', 'H7': 'Môi dày', 'H8': 'Môi mỏng',
    'H9': 'Môi trái tim', 'H10': 'Tai to', 'H11': 'Tai nhỏ', 'H12': 'Gò má cao',
    'H13': 'Gò má thấp', 'H14': 'Lông mày rậm', 'H15': 'Lông mày mỏng', 'H16': 'Trán cao',
    'H17': 'Trán thấp', 'H18': 'Mặt trái soan', 'H19': 'Mặt vông', 'H20': 'Mặt tròn',
    'H21': 'Cổ cao', 'H22': 'Cổ thấp', 'H23': 'Tay thon', 'H24': 'Tay to',
    'H25': 'Chân dài', 'H26': 'Chân ngắn', 'H27': 'Vai rộng', 'H28': 'Dáng cao người cao',
    'H29': 'Dáng người thấp', 'H30': 'Dáng người thon thả'
}

# Tập kết luận mức 1
conclusion_levels_1 = {
    'N1': 'Nhóm người hướng ngoại', 'N2': 'Nhóm người hướng nội', 'N3': 'Nhóm người hướng trung'
}

rules_1 = {
    'L1': {'conditions': ['T10'], 'conclusion': 'N1'},
    'L2': {'conditions': ['T6'], 'conclusion': 'N2'},
    'L3': {'conditions': ['T9'], 'conclusion': 'N2'},
    'L4': {'conditions': ['T10', 'T6'], 'conclusion': 'N1'},
    'L5': {'conditions': ['T10', 'T9'], 'conclusion': 'N1'},
    'L6': {'conditions': ['T6', 'T9'], 'conclusion': 'N2'},
    'L7': {'conditions': ['T10', 'T6', 'T9'], 'conclusion': 'N3'},
    'L8': {'conditions': ['T10', 'T8'], 'conclusion': 'N1'},
    'L9': {'conditions': ['T6', 'T8'], 'conclusion': 'N2'},
    'L10': {'conditions': ['T9', 'T8'], 'conclusion': 'N2'},
    'L11': {'conditions': ['T10', 'T3'], 'conclusion': 'N1'},
    'L12': {'conditions': ['T6', 'T3'], 'conclusion': 'N2'},
    'L13': {'conditions': ['T9', 'T3'], 'conclusion': 'N2'},
    'L14': {'conditions': ['T10', 'T1'], 'conclusion': 'N1'},
    'L15': {'conditions': ['T6', 'T1'], 'conclusion': 'N2'},
    'L16': {'conditions': ['T9', 'T1'], 'conclusion': 'N2'},
    'L17': {'conditions': ['T10', 'T4'], 'conclusion': 'N1'},
    'L18': {'conditions': ['T6', 'T4'], 'conclusion': 'N2'},
    'L19': {'conditions': ['T9', 'T4'], 'conclusion': 'N2'},
    'L20': {'conditions': ['T10', 'T2'], 'conclusion': 'N1'},
    'L21': {'conditions': ['T6', 'T2'], 'conclusion': 'N2'},
    'L22': {'conditions': ['T9', 'T2'], 'conclusion': 'N2'},
    'L23': {'conditions': ['T10', 'T5'], 'conclusion': 'N1'},
    'L24': {'conditions': ['T6', 'T5'], 'conclusion': 'N2'},
    'L25': {'conditions': ['T9', 'T5'], 'conclusion': 'N2'},
    'L26': {'conditions': ['T10', 'T8', 'T6'], 'conclusion': 'N1'},
    'L27': {'conditions': ['T6', 'T9', 'T1'], 'conclusion': 'N2'},
    'L28': {'conditions': ['T10', 'T3', 'T6'], 'conclusion': 'N1'},
    'L29': {'conditions': ['T10', 'T4', 'T9'], 'conclusion': 'N1'},
    'L30': {'conditions': ['T6', 'T8', 'T9'], 'conclusion': 'N2'},
}

conclusion_levels_2 = {
    'KL1': 'Số lãnh đạo', 'KL2': 'Số phát đạt', 'KL3': 'Số sung túc',
    'KL4': 'Số lận đận', 'KL5': 'Số bình an', 'KL6': 'Số nghèo khổ',
    'KL7': 'Số thọ', 'KL8': 'Số phú quý', 'KL9': 'Số tài giỏi',
    'KL10': 'Số tri kỷ', 'KL11': 'Số đam mê', 'KL12': 'Số tài nghệ',
    'KL13': 'Số bình yên', 'KL14': 'Số lãnh đạo', 'KL15': 'Số nhẫn nại',
    'KL16': 'Số linh hoạt', 'KL17': 'Số sáng suốt', 'KL18': 'Số nhân ái',
    'KL19': 'Số độc lập', 'KL20': 'Số đổi mới', 'KL21': 'Số dung hòa',
    'KL22': 'Số hào hiệp', 'KL23': 'Số hài hước', 'KL24': 'Số trưởng thành',
    'KL25': 'Số khám phá', 'KL26': 'Số thông thái', 'KL27': 'Số an nhàn',
    'KL28': 'Số tự do', 'KL29': 'Số hạnh phúc', 'KL30': 'Số vững bền',
}

rules_2 = {
    'R1': {'conditions': ['H1', 'H5', 'L6'], 'conclusion': 'KL5'},
    'R2': {'conditions': ['H2', 'L6'], 'conclusion': 'KL19'},
    'R3': {'conditions': ['H1', 'H3', 'L3'], 'conclusion': 'KL12'},
    'R4': {'conditions': ['H2', 'L1', 'H16'], 'conclusion': 'KL3'},
    'R5': {'conditions': ['H3', 'H14', 'L6'], 'conclusion': 'KL20'},
    'R6': {'conditions': ['H4', 'H7', 'L3'], 'conclusion': 'KL7'},
    'R7': {'conditions': ['H1', 'H2', 'L6'], 'conclusion': 'KL14'},
    'R8': {'conditions': ['H2', 'L2', 'H12'], 'conclusion': 'KL22'},
    'R9': {'conditions': ['H3', 'L3'], 'conclusion': 'KL25'},
    'R10': {'conditions': ['H4', 'L6'], 'conclusion': 'KL2'},
    'R11': {'conditions': ['H5', 'H6', 'L1'], 'conclusion': 'KL8'},
    'R12': {'conditions': ['H6', 'L2'], 'conclusion': 'KL26'},
    'R13': {'conditions': ['H7', 'H9', 'L3'], 'conclusion': 'KL9'},
    'R14': {'conditions': ['H8', 'H18', 'L6'], 'conclusion': 'KL4'},
    'R15': {'conditions': ['H9', 'H5', 'L1'], 'conclusion': 'KL17'},
    'R16': {'conditions': ['H10', 'H13', 'L1'], 'conclusion': 'KL23'},
    'R17': {'conditions': ['H11', 'L3'], 'conclusion': 'KL6'},
    'R18': {'conditions': ['H12', 'L1', 'H7'], 'conclusion': 'KL15'},
    'R19': {'conditions': ['H13', 'H9', 'L3'], 'conclusion': 'KL18'},
    'R20': {'conditions': ['H14', 'H4', 'L1'], 'conclusion': 'KL11'},
    'R21': {'conditions': ['H15', 'L1', 'H16'], 'conclusion': 'KL1'},
    'R22': {'conditions': ['H16', 'H1'], 'conclusion': 'KL27'},
    'R23': {'conditions': ['H17', 'H2'], 'conclusion': 'KL13'},
    'R24': {'conditions': ['H18', 'H10', 'L2'], 'conclusion': 'KL28'},
    'R25': {'conditions': ['H19', 'H7', 'L4'], 'conclusion': 'KL21'},
    'R26': {'conditions': ['H1', 'H5'], 'conclusion': 'KL10'},
    'R27': {'conditions': ['H2', 'H12'], 'conclusion': 'KL30'},
    'R28': {'conditions': ['H3', 'H18', 'L3'], 'conclusion': 'KL24'},
    'R29': {'conditions': ['H1', 'H9', 'L5'], 'conclusion': 'KL16'},
    'R30': {'conditions': ['H2', 'H4', 'L3'], 'conclusion': 'KL29'},
    'R31': {'conditions': ['H3', 'H10', 'L6'], 'conclusion': 'KL12'},
    'R32': {'conditions': ['H4', 'H11', 'L2'], 'conclusion': 'KL6'},
    'R33': {'conditions': ['H5', 'H12', 'L1'], 'conclusion': 'KL18'},
    'R34': {'conditions': ['H6', 'H13', 'L2'], 'conclusion': 'KL22'},
    'R35': {'conditions': ['H7', 'H14', 'L3'], 'conclusion': 'KL11'},
    'R36': {'conditions': ['H8', 'H15', 'L1'], 'conclusion': 'KL9'},
    'R37': {'conditions': ['H9', 'H16', 'L6'], 'conclusion': 'KL30'},
    'R38': {'conditions': ['H10', 'H17', 'L5'], 'conclusion': 'KL28'},
    'R39': {'conditions': ['H11', 'H18', 'L3'], 'conclusion': 'KL21'},
    'R40': {'conditions': ['H12', 'H19', 'L4'], 'conclusion': 'KL27'},
    'R41': {'conditions': ['H13', 'H20', 'L1'], 'conclusion': 'KL16'},
    'R42': {'conditions': ['H14', 'H21', 'L2'], 'conclusion': 'KL4'},
    'R43': {'conditions': ['H15', 'H22', 'L1'], 'conclusion': 'KL12'},
    'R44': {'conditions': ['H16', 'H23', 'L3'], 'conclusion': 'KL10'},
    'R45': {'conditions': ['H17', 'H24', 'L1'], 'conclusion': 'KL6'},
    'R46': {'conditions': ['H18', 'H25', 'L5'], 'conclusion': 'KL29'},
    'R47': {'conditions': ['H19', 'H26', 'L4'], 'conclusion': 'KL11'},
    'R48': {'conditions': ['H20', 'H27', 'L3'], 'conclusion': 'KL18'},
    'R49': {'conditions': ['H21', 'H28', 'L2'], 'conclusion': 'KL20'},
    'R50': {'conditions': ['H22', 'H29', 'L1'], 'conclusion': 'KL16'},
}

# lời khuyên
advices = {
    'KL1': 'Vững tin vào con đường mình chọn, bạn là người dẫn đầu số mệnh.',
    'KL2': 'Kiên trì và sáng suốt, thành công lớn lao sẽ đến với bạn.',
    'KL3': 'Giữ lòng rộng rãi và nhân hậu, tài lộc sẽ luôn đến bên bạn.',
    'KL4': 'Thận trọng trong tình cảm và công việc, khó khăn chỉ là tạm thời.',
    'KL5': 'Bình tĩnh và hài lòng với những gì mình có, cuộc sống sẽ yên ổn.',
    'KL6': 'Chia sẻ và giúp đỡ người khác, vận mệnh sẽ dần chuyển tốt hơn.',
    'KL7': 'Sống an nhiên, tránh xa lo toan, số mệnh đã dành sự trường thọ.',
    'KL8': 'Giữ tâm ngay thẳng và chăm chỉ làm việc, tài lộc sẽ không ngừng đến.',
    'KL9': 'Học hỏi và sáng tạo mỗi ngày, tri thức là con đường thành công.',
    'KL10': 'Đối đãi chân thành với mọi người xung quanh, bạn sẽ có tri kỷ tốt.',
    'KL11': 'Sống hết mình cho đam mê, trái tim sẽ dẫn lối hạnh phúc viên mãn.',
    'KL12': 'Khéo léo trong công việc và đối nhân xử thế sẽ được tôn trọng.',
    'KL13': 'Tĩnh lặng và không tranh đua, bạn sẽ đạt được sự bình an trong tâm.',
    'KL14': 'Quyết đoán và kiên định, bạn sinh ra để truyền cảm hứng người khác.',
    'KL15': 'Kiên nhẫn chịu đựng mọi khó khăn, nhẫn nại mang lại thành công bền vững.',
    'KL16': 'Thích nghi và biến đổi linh hoạt, cơ hội tốt sẽ đến bên bạn.',
    'KL17': 'Đừng ngừng suy nghĩ sâu sắc và cẩn trọng, đó là chìa khóa tương lai.',
    'KL18': 'Giúp đỡ mọi người xung quanh, lòng tốt của bạn sẽ mang lại phước lành.',
    'KL19': 'Tự tin và tự chủ trong mọi việc, số mệnh ban sức mạnh độc lập.',
    'KL20': 'Đừng ngần ngại thay đổi bản thân, sự đổi mới mang lại thành công.',
    'KL21': 'Giữ cân bằng giữa công việc và cuộc sống, bạn sẽ luôn tìm thấy hạnh phúc.',
    'KL22': 'Sống trượng nghĩa và bảo vệ lẽ phải, số mệnh đã định bạn là người hào hiệp.',
    'KL23': 'Giữ sự hóm hỉnh và vui tươi, tiếng cười giúp bạn vượt qua khó khăn.',
    'KL24': 'Trưởng thành qua từng trải nghiệm, sự điềm tĩnh sẽ đưa bạn tới viên mãn.',
    'KL25': 'Mở rộng tầm nhìn và tìm tòi, bạn sẽ đạt nhiều thành tựu lớn.',
    'KL26': 'Trau dồi kiến thức và trí tuệ, sự thông thái giúp bạn dẫn dắt người khác.',
    'KL27': 'Sống chậm lại và tận hưởng, cuộc sống an nhàn đang chờ bạn.',
    'KL28': 'Tự do và thoải mái theo đuổi đam mê, đừng để gì ràng buộc.',
    'KL29': 'Trân trọng những điều nhỏ bé xung quanh, bạn sẽ luôn có hạnh phúc bền lâu.',
    'KL30': 'Sự kiên nhẫn và vững vàng đưa bạn vượt qua mọi khó khăn đạt ổn định.',
}